spring:
  cloud:
    gateway:
      routes:
        - id: edu-ad
          uri: lb://edu-ad
          predicates:
            - Path=/api/ad/**
        - id: edu-user
          uri: lb://edu-user
          predicates:
            - Path=/api/user/**
        - id: edu-resource
          uri: lb://edu-resource
          predicates:
            - Path=/api/oss/**
server:
  port: 9000