spring:
  cloud:
    gateway:
      routes:
        - id: edu-ad
          uri: lb://edu-ad
          predicates:
            - Path=/edu-ad/**
          filters:
            - StripPrefix=1
        - id: edu-user
          uri: lb://edu-user
          predicates:
            - Path=/edu-user/**
          filters:
            - StripPrefix=1
server:
  port: 9001