spring:
  cloud:
    gateway:
      routes:
        - id: sentinel-demo-router
          uri: lb://sentinel-client
          predicates:
            - Path=/hello/**
    sentinel:
      enabled: true
      transport:
        dashboard: localhost:8080
        port: 8719